# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- beta
- develop

pr:
- master
- beta
- develop

jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'npm ci'

  - script: npm run build
    displayName: 'npm run build'

  - script: npm test
    displayName: 'Run Tests'
